name: polo
version: '18.3.1b'
summary: Polo File Manager
description: |
  Advanced file manager for Linux written in Vala. Supports multiple panes (single, dual, quad) with multiple tabs in each pane. Supports archive creation, extraction and browsing. Support for cloud storage; running and managing KVM images, modifying PDF documents and image files, booting ISO files in KVM, and writing ISO files to USB drives.
grade: devel #stable once ready
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  polo:
    command: bin/polo
    plugs:
      - unity7
      - x11
      - network
      - desktop
      - desktop-legacy
      - gsettings
      - home

parts:
  client:
    plugin: nil
    source: https://github.com/teejee2008/polo/archive/v18.3-beta.tar.gz
    
    build-packages:
      - autotools-dev
      - valac
      - libgtk-3-dev
      - libgee-0.8-dev
      - libvte-2.91-dev
      - libjson-glib-dev
      - libxml2-dev
      
    stage-packages:
      - p7zip
      - gvfs
      - rsync
      - rclone
      - pv
      - lzop
      - libvte-2.91
      - libgee-0.8-2
      - libvte-2.91-0
      - libjson-glib-1.0-0
      - libxml2
      - ffmpeg
      - mediainfo
      - p7zip-full
      - p7zip-rar
      - tar
      - gzip 
      - pigz
      - bzip2 
      - pbzip2
      - xz-utils
      - fish
      - qemu-kvm
      - qemu-utils
      - gvfs-bin
      - gvfs-backends
      - wget

    build: |
      make
    install: |
      DESTDIR=$SNAPCRAFT_PART_INSTALL make install
